### ISSUE TITLE
OpenShift server

### ISSUE THREAD

**Issue by jenbrannstrom** [TapTapMobile/narconon#5]
Please can you move the page to this server/account

user: narconon@taptap.mobi
pass: narconon@taptap.mobi

**Comment by shailesh91** [comment]
I have moved the page to this location https://narconon-taptapmobi.rhcloud.com/.

**Comment by jenbrannstrom** [comment]
thanks,
the response time is dreadfully slow. The page loads in about a minute. Is this because of a server config?

**Comment by shailesh91** [comment]
I just loaded it as it is from the GitHub repo. I have not worked on it as
yet. I am not sure what the problem is.

On Sunday, February 22, 2015, Jen Brannstrom notifications@github.com
wrote:

> thanks,
> the response time is dreadfully slow. The page loads in about a minute. Is
> this because of a server config?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TapTapMobile/narconon/issues/5#issuecomment-75436263.

## 

## 

Regards
Shailesh Goel

Email   : shailesh912@gmail.com
Skype  : shailesh916
Phone  : +91-9780493275

**Comment by jenbrannstrom** [comment]
ok
